project:
  type: book
  output-dir: docs # HTML
  # output-dir: pdfs
  preview:
    port: 7771
    browser: false
  resources:
    - "data/*.mp3"
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!to_do.qmd"

lang: ko-KR

# ---------------------------------- #
book:
  title: "챗GPT 확률통계"
  reader-mode: true
  subtitle: "인공지능 데이터 사이언스 기본기"
  author:
    - name: "이광춘"
      affiliations: "공익법인 한국 R 사용자회"
  page-footer:
    left: |
      챗GPT 쿼토 책은 소프트웨어 카펜트리 ***** 번역한 것이 포함되어 있습니다.
    right: |
      순수하게 <a href="https://quarto.org/">쿼토(Quarto)</a>로 제작되었습니다.

  cover-image: images/book_cover.jpg
  favicon: images/logo.png
  site-url: https://r2bit.com/gpt-stat/
  repo-url: https://github.com/bit2r/gpt-stat/
  repo-branch: main
  repo-actions: [edit, issue]

  google-analytics: "UA-229551680-1"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
# ---------------------------------- #
  chapters:
    - index.qmd
    # - part: "확률"
    #   chapters:
    #     - data_mgmt.qmd
    #     - database_mgmt.qmd
    #     - document.qmd
    #     - document_auto.qmd
    #     - model.qmd
    #     - model_value.qmd

    - part: "사례연구"
      chapters:
        - cs_nightingale.qmd
        - cs_napolean.qmd
        - u_boats.qmd
        - cs_prussia.qmd
        - cs_german_tank.qmd
        - cs_bomber.qmd

    # - part: "통계책"
    #   chapters:
    #     - webr.qmd
    #     - shinylive.qmd
        # - clt.qmd
    - references.qmd

# ---------------------------------- #
format:
  html:
    mermaid:
      theme: neutral # https://quarto.org/docs/authoring/diagrams.html#mermaid-theming
    theme:
      - cosmo
      - r2bit.scss
    number-depth: 3
    number-sections: true
    colorlinks: true
    # cite-method: biblatex
    code-overflow: wrap
    code-link: true

    author-meta: "이광춘"
    include-in-header: "plausible.html"
    callout-appearance: simple

    # 마크다운 표 캡션 위치
    tbl-cap-location: bottom
# ---------------------------------- #
filters:
  - lightbox
  # - parse-latex
  # - include-code-files
  # - webr
  # - shinylive
lightbox: auto

code-annotations: hover

bibliography: references.bib
link-citations: false

# ---------------------------------- #

engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: true
    code-overflow: code-overflow
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true
editor_options:
  chunk_output_type: console

editor:
  markdown:
    wrap: 72



